spring:
  application:
    name: babee-transmission-project
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: true
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driverClassName: org.postgresql.Driver
    
file:
  upload-dir: src/main/resources/uploads


